### ISSUE TITLE
You are not authorized to perform: lambda:GetLayerVersion

### ISSUE THREAD

**Issue by AlainODea** [theam/aws-lambda-haskell-runtime#1]
I get this error in the Lambda console:
```
You are not authorized to perform: lambda:GetLayerVersion
```

The logs have this error:
```json
{
  "errorType": "Runtime.ExitError",
  "errorMessage": "RequestId: d845feca-fceb-11e8-a5cd-8561bb36db60 Error: Couldn't find valid bootstrap(s): [/var/task/bootstrap /opt/bootstrap]"
}
```

I think the layer needs a resource policy to allow other accounts to pull it.

I may be wrong. I may just have a silly IAM policy.

I've tried adding **lambda:GetLayerVersion** on **arn:aws:lambda:us-east-1:785355572843:layer:haskell-runtime:2** and even **lambda:\*** on **\***.

The Layer `arn:aws:lambda:us-east-1:785355572843:layer:haskell-runtime:2` does not appear to be accessible to other accounts.

I think this might fix it:
```
aws lambda add-layer-version-permission --layer-name haskell-runtime \
--statement-id allow-everyone --version-number 2 --principal '*' \
--action lambda:GetLayerVersion
```

That's based on a doc on Layer Permissions here:
https://docs.aws.amazon.com/lambda/latest/dg/configuration-layers.html#configuration-layers-permissions

**Comment by AlainODea** [comment]
I'm wrong here based on AWS CLI using the same credentials as I use for the AWS Console:

```
aws lambda get-layer-version --layer-name arn:aws:lambda:us-east-1:785355572843:layer:haskell-runtime --version-number 2
{
    "Content": {
        "Location": "https://prod-04-2014-layers.s3.amazonaws.com/snapshots/785355572843/haskell-runtime-<SNIP>",
        "CodeSha256": "I945VFYH+wngJH/a2a0cetmTIs06KUIfGLTOS8a0YVo=",
        "CodeSize": 4894510
    },
    "LayerArn": "arn:aws:lambda:us-east-1:785355572843:layer:haskell-runtime",
    "LayerVersionArn": "arn:aws:lambda:us-east-1:785355572843:layer:haskell-runtime:2",
    "Description": "",
    "CreatedDate": "2018-12-08T00:07:41.867+0000",
    "Version": 2
}
```

This is a region issue. I tried Canada - Central. I think Lambda layers may have to be in the same region. It's odd that it manifests as a permissions issue.

**Comment by AlainODea** [comment]
This also doesn't work from us-east-2 or us-west-1. This is expected. I'm leaving the note here so that others (hopefully) don't raise it separately.

This is amazing by the way. Awesome work. 2.2MB AWS Lambda Functions running Haskell are awesome.

**Comment by nrolland** [comment]
For confused user, to change region, it's up on top on the web, near your name.

**Comment by AlainODea** [comment]
@nrolland indeed :)

Here's my rough article explaining how to do this with regions outside US-East-1:
https://blog.alainodea.com/en/article/511/haskell-aws-lambda-runtime-outside-us-east-1

**Comment by Kalm004** [comment]
@nrolland  @AlainODea we have deployed the runtime to all regions, you can use it now like this:

arn:aws:lambda:<YOUR REGION>:785355572843:layer:haskell-runtime:2

We had an issue with the deployment of us-east-2 so if you are using that region, please change the version from 2 to 10.

I'll add this information to the readme soon.
