### ISSUE TITLE
Mandatory authorizer field breaks Lambdas without authorizer

### ISSUE THREAD

**Issue by hugoflug** [theam/aws-lambda-haskell-runtime#101]
In 8f0698f318d55ed37fae5ce5390f1085fa866039, the `authorizer` field was added to ApiGatewayRequestContext.
However, Lambdas doesn't always have an authorizer. We have a use case where we want to do the auth-checking inside the lambda itself, and because of this change we can't use this library.

Would it be OK to open a PR to make this field a Maybe?

**Comment by NickSeagull** [comment]
I guess that it wouldn't be any problem, although maybe @dnikolovv could have more context than me for this

**Comment by dnikolovv** [comment]
I think a `Maybe` would work great! Sorry for the breakage :(

**Comment by NickSeagull** [comment]
Closed with  #102
