### ISSUE TITLE
Sometimes a function goes into a stall

### ISSUE THREAD

**Issue by y-taka-23** [theam/aws-lambda-haskell-runtime#18]
I'm trying to deploy a lambda function written in Haskell, and find that some of deployments fail by timeout, though the source code files are exactly same.

When a function fails, then re-invocation nor re-deploy doesn't matter. That is, you have to (at least) build the binary again. But I've not found the minimal condition when and why the trouble rises.

Sorry for the lack of a procedure for reproducing. Do you have any idea?

## Environment
- built in `fpco/stack-build:lts-12.13` by `stack build --docker`
- `stack clean --full --docker` everytime
- aws-lambda-haskell-runtime-1.0.7
- arn:aws:lambda:ap-northeast-1:785355572843:layer:aws-haskell-runtime:2

## Source

`src/HelloWorld.hs`
```haskell
{-# LANGUAGE DeriveGeneric     #-}
{-# LANGUAGE OverloadedStrings #-}

module HelloWorld where

import           Aws.Lambda.Runtime   (Context)
import           Data.Aeson           (ToJSON, encode)
import qualified Data.ByteString.Lazy as BS
import           Data.Default.Class   (def)
import qualified Data.Text            as T
import qualified Data.Text.Encoding   as T
import           GHC.Generics         (Generic)
import           Network.HTTP.Req

handler :: () -> Context -> IO (Either String APIGatewayProxyResponse)
handler _ _ = do
    bs <- runReq def $ do
        req GET (https "checkip.amazonaws.com") NoReqBody bsResponse mempty
    let ip = T.init $ T.decodeUtf8 $ responseBody bs
        res = Response "hello world" ip
        pres = APIGatewayProxyResponse 200
                (T.decodeUtf8 $ BS.toStrict $ encode res)
    return $ Right pres

data Response = Response {
      message  :: T.Text
    , location :: T.Text
    } deriving (Generic)

instance ToJSON Response

-- to integrate with API Gateway, the response body should be string-ified.
data APIGatewayProxyResponse = APIGatewayProxyResponse {
      statusCode :: Int
    , body       :: T.Text
    } deriving (Generic)

instance ToJSON APIGatewayProxyResponse
```

`app/Main.hs`
```haskell
{-# LANGUAGE OverloadedStrings #-}
{-# LANGUAGE TemplateHaskell   #-}

module Main where

import           Aws.Lambda.Configuration
import           Aws.Lambda.Runtime

import qualified HelloWorld

configureLambda
```

## Response

succeeded case:
```json
{ "statusCode": 200, "body": "{ \"location\", \"198.51.100.123\", \"message\": \"hello world\" }" }
```

failed case:
```json
{ "errorMessage":"2019-01-17T07:43:58.370Z 51ba6bb5-5ca1-4e7d-96b3-6e54490dd39a Task timed out after 20.02 seconds" }
```

**Comment by NickSeagull** [comment]
Could you try to use the `1.0.9` version of the library and see if the issue persists?

I remember that some issue related to timeouts was fixed in 1.0.8 or 1.0.9

**Comment by tainguyenbui** [comment]
what is the timeout for your function? Does this normally happens the first time you call it after a while?

**Comment by y-taka-23** [comment]
Even after upgrading to 1.0.9, the issue remains. Conditions for reproducing are still unclear, so I'd like to share my SAM-based Stack template I'm using to easily deploy them multiple times:

```console
$ stack new sam-app https://gist.githubusercontent.com/y-taka-23/411dbc7e1c9ccd3020ff5aee3a127064/raw/b106c02a3fa02f828d8b5c25536f1c8e62cc5f80/aws-sam.hsfiles
$ cd sam-app
$ make
$ aws cloudformation package --template-file template.yaml --output-template-file packaged.yaml --s3-bucket <YOUR_BUCKET_NAME>
$ aws cloudformation deploy --template-file packaged.yaml --stack-name <YOUR_STACK_NAME> --capabilities CAPABILITY_IAM
```

The output form the CloudFormation includes an REST endpoint:

```
https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/hello/
```

If you try to deploy-delete the stack some times and access the endpoint, eventually you can see:

```
{"message": "Internal server error"}
```

**Comment by tainguyenbui** [comment]
@y-taka-23 just to clarify.

From what I can see given the above information. It is not a problem with deploying or deleting your functions. In fact, when you are given as a response from CloudFormation and endpoint it means that your functions have been successfully deployed.

Is there any chance that you could share with us the CloudWatch logs related to your Lambda Function that are generated when you receive

```
{"message": "Internal server error"}
```

These logs are invocation based so it should be fairly easy to find it.

To access CloudWatch logs:
1. Log in to your AWS Console
2. Go to CloudWatch
3. Click on Logs on the left-hand-side menu
4. Click on your AWS Lambda Log Group, e.g. /aws/lambda/<YOUR_STACK_NAME>-hello
5. Clock on the latest log if the error just happened (you may need to refresh to see the latest log)
6. expand all as "text" by clicking "Text" radio button on the top right corner
7. Paste the log here

Thanks a lot!

**Comment by tainguyenbui** [comment]
Thanks for the log. Unfortunaly, nothing much we can extract from them.

Any chance we could give it a bit more memory? perhaps 512 or 1024MB? also... Serverless Artillery is a great tool to hit your exposed endpoint. Would you mind testing it with 30 invocations pero second during 120 seconds for example to see the proportion of them that fail? Ideally, adding some logging would help too identifying where what bit is causing troubles.

**Comment by y-taka-23** [comment]
> Any chance we could give it a bit more memory?

You pointed it out clearly!

I did load tests by Artillery with 3600 requests (30 req/sec * 120 sec) and got the following results. Maybe I have to provision more memory, at least 512 MB.

| MemorySize (MB) | 200 OK | 502 Bad Gateway|
|--:|--:|--:|
| 128 | 146 | 3454 |
| 256 | 3171 | 429 |
| 512 | 3600 | 0 |
| 768 | 3592 | 8 |
| 1024 | 3595 | 5 |

I'm afraid that we have another anomaly: The results show that the function requires more memory, On the other hand, CloudWatch logs from successful invocations say it requires at most 100 MB or so. From where the difference comes?

```
START RequestId: 53331eab-a73b-478c-af70-a4ed37f2f522 Version: $LATEST
END RequestId: 53331eab-a73b-478c-af70-a4ed37f2f522
REPORT RequestId: 53331eab-a73b-478c-af70-a4ed37f2f522	Duration: 1949.68 ms	Billed Duration: 2000 ms Memory Size: 512 MB	Max Memory Used: 104 MB	
```

**Comment by tainguyenbui** [comment]
hi @y-taka-23 the above is AWESOME! really useful information.

With the above results we can see that the reason why it was timing out was due to the Lambda taking more than 5 seconds to complete with 128MB and execution time goes down as you increase memory.

> _"CloudWatch logs from successful invocations say it requires at most 100 MB or so"_

When provisioning more memory, you are not only provisioning more memory but also more CPU. According to AWS:

> ["if you allocate 256 MB memory, your Lambda function will receive twice the CPU share than if you allocated only 128 MB"](https://docs.aws.amazon.com/lambda/latest/dg/resource-model.html)

At this point and with some data in hand my suggestion will be to allocate more memory, at least 512 MB and have a look at the execution time with 512 MB and 1024 MB or even 1280 MB.

> ["More memory doesn't always mean more expensive"](https://blog.binaris.com/lambda-pricing-pitfalls)

We will look on our side what can be done in order to enhance the runtime.

thanks a lot and have a great day!

**Comment by y-taka-23** [comment]
> my suggestion will be to allocate more memory, at least 512 MB 

Got it, Thanks for the information!
