### ISSUE TITLE
layer

### ISSUE THREAD

**Issue by nrolland** [theam/aws-lambda-haskell-runtime#2]
I get an error adding the layer  `arn:aws:lambda:us-east-1:785355572843:layer:haskell-runtime:2`

`You are not authorized to perform: lambda:GetLayerVersion.`

(might be a pb with my config, but it says 

> If you would like to use a layer published in another account, you need to ensure the layer publisher has set the correct permissions on the layer version to make it available in your account.

)

**Comment by tainguyenbui** [comment]
Hi! there was someone with the same issue and it looked like it was resolved by changing regions
https://github.com/theam/aws-lambda-haskell-runtime/issues/1

**Comment by nrolland** [comment]
Indeed, thanks !
