### ISSUE TITLE
change configureLamba to generateLambdaDispatcher in scaffold

### ISSUE THREAD

**Issue by JonathanLorimer** [theam/aws-lambda-haskell-runtime#35]
when one tries to build the new scaffold (2.0.0+) the template Haskell function in main is still ```configureLambda``` when it should be ```generateLambdaDispatcher``` as far as I can tell. I had to look through the source to find this function.

**Comment by NickSeagull** [comment]
Thanks for reporting this! Just fixed it in https://github.com/theam/aws-lambda-haskell-runtime/commit/8822609d7e22b6e1eb27f1323af4dcab08f09bc1
