### ISSUE TITLE
Getting error when following instructions in docs

### ISSUE THREAD

**Issue by ChristophP** [theam/aws-lambda-haskell-runtime#47]
I followed the instructions in the docs which said:
> If you currently have a project, you can add this package by adding,
to the stack.yaml file: ```extra-deps: - aws-lambda-haskell-runtime-2.0.0```

I get the following error on `stack build`:

![image](https://user-images.githubusercontent.com/5880236/64485888-24d46400-d226-11e9-9a4a-7ef5d8899473.png)

I can resolve it by using `aws-lambda-haskell-runtime-2.0.1.` in the `extra-deps` but it would be nice if the docs were correct. Especially to not scare of beginners. I think Haskell lambdas would be a great and low-risk entry point for many trying to get Haskell into production.

**Comment by NickSeagull** [comment]
I just fixed this on #48 , take a look ! 😊

**Comment by ChristophP** [comment]
@NickSeagull Great, I will have a look.
