### ISSUE TITLE
Swedish characters in response turn into gibberish when using API gateway

### ISSUE THREAD

**Issue by dnikolovv** [theam/aws-lambda-haskell-runtime#79]
If you use `UseWithApiGateway` and return something that contains swedish characters (latin1 encoded), they will be turned into gibberish.

E.g.

`Tack fÃ¶r din bestÃ¤llning` instead of `Tack för din beställning`.

**Comment by talw** [comment]
I have a similar problem, but with Japanese characters.

Using API Gateway the behaviour can be classified as follows:

Marking the body type X, the handler's response type is:
IO (Either (ApiGatewayResponse Text) (ApiGatewayResponse X))

When X is aeson's `Value`, and I put `String "ネ"` (or any JSON object containing Japanese text) a different character is returned from lambda: `ã`
However, when X is `String` or `Text` and I simply put `"ネ"` (OverloadedStrings is used) the correct character is returned from lambda: `ネ`

**Comment by talw** [comment]
The problem seems to be with the function utility function `toJSONText`:

```
λ> import RIO.Text
λ> import Data.Text.IO
λ> writeFile "/tmp/wrong" $ toJSONText $ A.String "ネ"
λ> writeFile "/tmp/correct" "ネ"
```

```
$ cat /tmp/wrong
"ã"
$ cat /tmp/right
ネ
```

**Comment by talw** [comment]
It is fixed by replacing the `unpack` with a `decodeUtf8` call, removing the `T.pack` and perhaps changing the ByteString's strictness as needed.
```
toJSONText :: ToJSON a => a -> Text
toJSONText = decodeUtf8 . LBS.toStrict . A.encode
```

**Comment by dnikolovv** [comment]
That's great @talw! Could you submit a PR?

**Comment by talw** [comment]
@dnikolovv Submitted
