### ISSUE TITLE
[Question] Fetching values from SSM from Haskell Lambda

### ISSUE THREAD

**Issue by EncodePanda** [theam/aws-lambda-haskell-runtime#94]
Hi, 

we are trying to retrieve a value from SSM within a Haskell Lambda (aws-lambda-haskell-runtime).
If we were writing this lambda using JavaScript we would do something like this:

```
(...)
const AWS = require('aws-sdk');
const SSM = new AWS.SSM({
  httpOptions: {
    connectTimeout: parseInt(process.env.CONNECT_TIMEOUT),
    timeout: parseInt(process.env.REQUEST_TIMEOUT),
  },
});
const response = await SSM.getParameter({
      Name: name,
      WithDecryption: true,
 }).promise();
(....)
```

Is there an equivalent call that we could run on the `aws-lambda-haskell-runtime`?

**Comment by andys8** [comment]
In my project we use `amazonka` in general for any aws services like dynamodb. So my first guess would be to use `amazonka-ssm`.

http://hackage.haskell.org/package/amazonka-ssm

Would that achieve what you want or is there a cause it needs to be lambda specific or can't be used?

**Comment by NickSeagull** [comment]
Yes, for calls to AWS services one would use `amazonka`. The runtime only should provide the events and so
